# Sample config.yaml file for MCP MITM Mem0
# Copy this file to config.yaml and fill in your actual values
# Note: Environment variables and .env file values take precedence over these settings

# Required configuration
openai_api_key: ""
mem0_provider: "openai"
model_name: "gpt-4o-mini"

# Optional configuration
auth_token: "your_auth_token_here"
server_host: "localhost"
server_port: 8000
debug: false

# Mem0 specific configuration
mem0_config:
  vector_db: "chroma"
  embedding_model: "text-embedding-ada-002"
