[project]
name = "mcp-mitm-mem0"
version = "0.1.0"
description = "Experimental external memory for your agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.4",
    "mem0ai",
    "mitmproxy>=12.1.1",
]

[dependency-groups]
lint = [
    "basedpyright>=1.29.4",
    "pylint>=3.3.7",
    "ruff>=0.11.13",
]


[tool.ruff]
preview = true
fix = true
unsafe-fixes = true
cache-dir = "~/.cache/ruff"
target-version = "py312"
output-format = "grouped"
extend = "ruff_defaults.toml"

[tool.ruff.analyze]
preview = true
detect-string-imports = true

[tool.ruff.lint]
preview = true
select = ["E4", "E7", "E9", "F", "B","C4","SIM","UP","S","N","I","Q","YTT"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
preview = true

#l ws h Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true
